"""
Build script for TLI Tracker.

Usage:
    python build/build.py          # Sync version + compile with Nuitka
    python build/build.py --sync   # Only sync version to version.iss
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
BUILD_DIR = Path(__file__).parent
VERSION_PY = ROOT / "app" / "version.py"
VERSION_ISS = BUILD_DIR / "version.iss"


def get_version() -> str:
    """Read version from app/version.py"""
    content = VERSION_PY.read_text()
    match = re.search(r'__version__\s*=\s*["\']([^"\']+)["\']', content)
    if not match:
        raise ValueError("Could not find __version__ in app/version.py")
    return match.group(1)


def sync_version() -> str:
    """Sync version from app/version.py to version.iss"""
    version = get_version()
    content = f'''; Version include file for Inno Setup
; Auto-generated by build.py - do not edit manually
#define MyAppVersion "{version}"
'''
    VERSION_ISS.write_text(content)
    print(f"Synced version {version} to version.iss")
    return version


def compile_nuitka() -> int:
    """Compile with Nuitka"""
    cmd = [
        sys.executable, "-m", "nuitka",
        "--standalone",
        "--enable-plugin=pyside6",
        f"--include-data-dir={ROOT / 'ui'}=ui",
        f"--include-data-file={ROOT / 'data' / 'item_ids.json'}=data/item_ids.json",
        f"--windows-icon-from-ico={ROOT / 'ui' / 'assets' / 'logo.ico'}",
        "--windows-console-mode=disable",
        f"--output-dir={ROOT / 'dist'}",
        "--mingw64",
        str(ROOT / "app" / "main.py"),
    ]

    print("Running Nuitka compilation...")
    print(" ".join(cmd))
    return subprocess.call(cmd)


def main():
    parser = argparse.ArgumentParser(description="Build TLI Tracker")
    parser.add_argument("--sync", action="store_true", help="Only sync version")
    args = parser.parse_args()

    sync_version()

    if args.sync:
        return 0

    return compile_nuitka()


if __name__ == "__main__":
    sys.exit(main())
